include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_returning_null_for_void
    - avoid_unnecessary_containers
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_in_for_each
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_await_in_return
    - use_key_in_widget_constructors